#ifndef GUILD_SYSTEM_H
#define GUILD_SYSTEM_H

/* Header file for Aevum-WoW 2014 */


enum guild_faction
{
    STEAMWHEEDLE_GOBLIN = 0,
    STORMWIND_HUMAN, //1,
    KUL_TIRAS_HUMAN, //2,
    ALTERAC_HUMAN, //3,
    STROMGUARD_HUMAN, //4,
    LORDAERON_HUMAN, //5,
    DALARAN_HUMAN, //6,
    GILNEAS_HUMAN, //7
    IRONFORGE_DWARF, //8,
    WILDHAMMER_DWARF, //9,
    DARK_IRON_DWARF, //10,
    GNOMEREGAN_GNOME, //11,
    DARNASSIAN_NIGHTELF, //12,
    SHEN_DRALAR_NIGHTELF, //13,
    EXODAR_DRAENEI, //14,
    BROKEN_DRAENEI, //15,
    QUELTHAS_BLOODELF, //16,
    QUELTHAS_HIGHELF, //17,
    THRALL_ORC, //18,
    DARK_HORDE_ORC, //19,
    CHAOS_ORC, //20,
    MAG_HAR_ORC, //21,
    JUNGLE_TROLL, //22,
    FOREST_TROLL, //23,
    ICE_TROLL, //24,
    SAND_TROLL, //25,
    BLOODHOOF_TAUREN, //26,
    GRIMTOTEM_TAUREN, //27,
    SCOURGE_UNDEAD, //28,
    FORSAKEN_UNDEAD, //29,
    INDEPENDENT_UNDEAD, //30,
    BILGEWATER_GOBLIN, //31,
    BANDIT_HUMAN, //32,
    ARGENT_HUMAN, //33,
    SCARLET_HUMAN //34
};

#endif
